///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SigninModel {
/*
{
  "accessToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImExYjQxZmFkYTIxN2FhYzMxMTRiZDMzYjVmMTFkNTEzIiwidHlwIjoiSldUIn0.eyJuYmYiOjE2Nzk2MDM3MTQsImV4cCI6MTY3OTYwNzMxNCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eXNlcnZlcml3b3JrLmJ0YXJnZS5jb20iLCJhdWQiOlsiaHR0cHM6Ly9pZGVudGl0eXNlcnZlcml3b3JrLmJ0YXJnZS5jb20vcmVzb3VyY2VzIiwiZXJwQXBpIl0sImNsaWVudF9pZCI6InJvLmNsaWVudCIsInN1YiI6IjY0ZmJiZWZhLTcyNjQtNGM5ZS04MjcyLTUwMDE1YjkyMjJjYyIsImF1dGhfdGltZSI6MTY3OTYwMzcxNCwiaWRwIjoibG9jYWwiLCJleHRlcm5hbF9pZCI6ImVkMjM2ZGNhLWM1YzEtNGFlOC1iMjU0LWYwNjkyZTg1YTkwOSIsInRlbmFudF9pZCI6IjQiLCJzY29wZSI6WyJlcnBBcGkiXSwiYW1yIjpbInB3ZCJdfQ.RVhGcmcIjftLplH2KfI7sA1dH3GDz4lILIzpJV6CbKwdjsD6INHgqxVmAuuVBpCskJOjWVPxPNIQM4WSeE5gLbCb94ihqqSD1xBQu6tXOAAKC6hISe2vImcJ123nOECObwH85gr_ZE7M_W7SZujAlHXTvBLRmQpeXk-YjCkfXDYFjaaK3B4nqGXPRLggNglzD9xR0Qljs1cjI2jyutU1RxIc_enJSXr-fXsKPa_02sQhL4A7-dyrvzUw6bU-3vaJsDO_saUl4cevt1Zjv4oYVnq7oDpkFqjYDteLGYY4DXpLh0HPHymkPBjXToDC0mM-mPstHZD9GqgMhI570FrNDA",
  "expiresIn": 3600,
  "tokenType": "Bearer"
}
*/

  String? accessToken;
  int? expiresIn;
  String? tokenType;
  String? userName;
  String? userId;
  String? refreshToken;

  SigninModel({
    this.accessToken,
    this.expiresIn,
    this.tokenType,
    this.userName,
    this.userId,
    this.refreshToken,
  });
  SigninModel.fromJson(Map<String, dynamic> json) {
    accessToken = json['accessToken']?.toString();
    expiresIn = json['expiresIn']?.toInt();
    tokenType = json['tokenType']?.toString();
    userName = json['userName']?.toString();
    userId = json['userId']?.toString();
    refreshToken = json['refreshToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['accessToken'] = accessToken;
    data['expiresIn'] = expiresIn;
    data['tokenType'] = tokenType;
    data['userName'] = userName;
    data['userId'] = userId;
    data['refreshToken'] = refreshToken;
    return data;
  }
}
